
public class Checker
{
	/* Static method that takes a Sudoku puzzle and returns a new puzzle with one number randomly changed */ 
	public static int[][] damage(int[][] puzzle)
	{
		int[][] newPuzzle = new int[puzzle.length][];
		for (int index = 0; index < puzzle.length; index++)
		{
			newPuzzle[index] = puzzle[index].clone();
		}

		int row = (int) (Math.random() * puzzle.length);
		int col = (int) (Math.random() * puzzle[puzzle.length - 1].length);
		int change;
		do
		{
			change = (int) (Math.random() * puzzle.length);
		} while (change == newPuzzle[row][col]);
		newPuzzle[row][col] = change;
		return newPuzzle;
	}

	public static void main(String[] args)
	{
		/* Sample Sudoku puzzle with the correct solution */
		int[][] sample =   {{5,3,4,6,7,8,9,1,2},
        					{6,7,2,1,9,5,3,4,8},
        					{1,9,8,3,4,2,5,6,7},
        					{8,5,9,7,6,1,4,2,3},
        					{4,2,6,8,5,3,7,9,1},
        					{7,1,3,9,2,4,8,5,6},
        					{9,6,1,5,3,7,2,8,4},
        					{2,8,7,4,1,9,6,3,5},
        					{3,4,5,2,8,6,1,7,9}};

		/* Sudoku puzzle with problems in the rows */
        int[][] sampleR =  {{5,3,4,6,7,8,9,1,2},
        					{6,7,2,1,9,5,3,4,8},
        					{1,9,8,3,4,2,5,6,7},
        					{8,5,9,7,6,1,4,2,3},
        					{4,2,3,8,5,3,7,9,1},
        					{7,1,6,9,2,4,8,5,6},
        					{9,6,1,5,3,7,2,8,4},
        					{2,8,7,4,1,9,6,3,5},
        					{3,4,5,2,8,6,1,7,9}};

		/* Sudoku puzzle with problems in the columns */
        int[][] sampleC =  {{5,3,4,6,7,8,9,1,2},
        					{6,7,2,1,9,5,3,4,8},
        					{1,9,8,3,4,2,5,6,7},
        					{8,5,9,7,6,1,4,2,3},
        					{4,2,6,5,8,3,7,9,1},
        					{7,1,3,9,2,4,8,5,6},
        					{9,6,1,5,3,7,2,8,4},
        					{2,8,7,4,1,9,6,3,5},
        					{3,4,5,2,8,6,1,7,9}};

		/* Sudoku puzzle with problems in the subsquares */
        int[][] sampleS =  {{5,3,4,6,7,8,9,1,2},
							{6,7,2,1,9,5,3,4,8},
							{1,9,8,3,4,2,5,6,7},
							{8,5,7,9,6,4,1,2,3},
							{4,2,6,8,5,3,7,9,1},
							{9,4,3,7,2,1,8,5,6},
							{7,6,1,5,3,9,2,8,4},
							{2,8,9,4,1,7,6,3,5},
							{3,1,5,2,8,6,4,7,9}};

		/* Sudoku puzzle with the problem generated by the damage method */
        int[][] badSample = damage(sample);
        
        SudokuChecker board = new SudokuChecker(sample);
        SudokuChecker board1 = new SudokuChecker(sampleR);
        SudokuChecker board2 = new SudokuChecker(sampleC);
        SudokuChecker board3 = new SudokuChecker(sampleS);
        SudokuChecker board4 = new SudokuChecker(badSample);
        System.out.println(board.checker());
        System.out.println("");
        System.out.println(board1.checker());
        System.out.println("");
        System.out.println(board2.checker());
        System.out.println("");
        System.out.println(board3.checker());
        System.out.println("");
        System.out.println(board4.checker());
	}
}
